Update cc and cmake dependencies to be compatible with Visual Studio 2022 (#1532)
without these updated cc and cmake, as old cc/cmake don't
know anything about existing Visual Studio 17 2022 compiler
prost-build crate will fail on x86_64-pc-windows-msvc host with the
following error:

```
error: failed to run custom build command for `prost-build v0.10.3`

Caused by:
  process didn't exit successfully: `C:\work\atomicDEX-API\target\release\build\prost-build-1ac4fc454bf4b145\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\prost-build-0.10.3\third-party\protobuf\cmake
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None

  --- stderr
  thread 'main' panicked at '

  unsupported or unknown VisualStudio version: 17.0
  if another version is installed consider running the appropriate vcvars script before building this crate
  ', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.46\src\lib.rs:877:25
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```